### ISSUE TITLE
Adding Text Boxes

### ISSUE THREAD

**Issue by SteveDoido** [leomontenegro6/aade#1]
Adding a Text Box makes the tool go back a few pages. It wouldn't be much of a problem if there was a way to instantly go to any page (perhaps after pressing the "..." button?).

**Comment by SteveDoido** [comment]
The tool saves the files in UTF-8, while the appropriate would've been UTF-8 without BOM.

**Comment by leomontenegro6** [comment]
Ambos os bugs relatados acima foram resolvidos na última atualização. SteveDoido confirmou no chat do discord que os scripts agora estão sendo gerados em UTF-8 sem BOM, e que o bug do botão "adicionar bloco" não está mais voltando para a página 1 da tabela.
