### ISSUE TITLE
Problema nas cores

### ISSUE THREAD

**Issue by Magalicia** [leomontenegro6/aade#3]
Quando ocorre um diálogo de pensamento,  o jogo para de ficar com a cor quando encontra a mensagem "{color: 0}"
com 2 ou mais diálogos, obviamente para quando chega nessa mesma mensagem enquanto segue a ordem do script
mas no AADE ele só deixa com cor azul somente o primeiro diálogo
exemplo de jogo:

{person: 22 173 173}{name: 512}{bgcolor: 769 8 31}{shake: 30 0}{color: 2}
(Droga!){p}

{speed: 5}
(Hmm...{wait: 20}
 talvez se eu tiver{b}
algo pra poder fazê-la{b}
falar...){color: 0}{p}

no jogo irá pintar os dois balões, na tool só o primeiro, já que o de baixo consideraria como um independente.
Às vezes a tool simplesmente corrige isso, então é questão de chance e é meio aleatório.

**Comment by leomontenegro6** [comment]
Corrigido no commit [7e3526a83b025e9baa7b2d67b8a5481deb166832](https://github.com/leomontenegro6/aade/commit/7e3526a83b025e9baa7b2d67b8a5481deb166832). Magalicia e Gamerulez, no canal do discord do grupo "jacu tem sabão", confirmaram que o problema não ocorre mais.
