### ISSUE TITLE
Problema em gerar gráficos alternando as versões

### ISSUE THREAD

**Issue by Magalicia** [leomontenegro6/aade#4]
O problema é simples de fazer, mas depende da sorte (ou azar) de acontecer.
O botão "gerar" para de funcionar às vezes executando essa troca de versão DS/3DS do mesmo texto, 
tendo que reiniciar a página quando acontece.

Relatório da última vez que deu erro:
*No "Nome da Prova/Perfil", comecei e inseri "Aline Sato" na versão 3DS e gerei o gráfico;
*Para poupar tempo, mudei pra versão DS e gerei o gráfico;
*Ainda na versão DS, inseri "Alice Sato" e gerei o gráfico;
*Mudei para poupar tempo para a versão 3DS e o botão de gerar parou de funcionar.

Apertei F12 e esse apareceu esses erros:
![coms](https://user-images.githubusercontent.com/32755465/33510204-a2768bfa-d6f0-11e7-8413-3f2ff9f7bafe.png)

**Comment by leomontenegro6** [comment]
Issue gerada no repositório da tool errada. Esse erro não ocorre no AADE, mas sim no AAIG:
https://github.com/leomontenegro6/aaig/issues

De todo modo, esse bug foi corrigido alguns meses atrás, e considerando que os usuários do Jacutem Sabão não tem reclamado mais sobre, estou dando essa issue como resolvida, assim fechando-a.
